services:
  - type: web
    name: publishjockey-backend
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_ACCESS_TOKEN_SECRET
        sync: false
      - key: JWT_REFRESH_TOKEN_SECRET
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRY
        value: 1h
      - key: JWT_REFRESH_TOKEN_EXPIRY
        value: 30d
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CSRF_SECRET
        sync: false
      - key: STRIPE_IMAGES_ADDON_100_PRICE_ID
        sync: false

crons:
  - name: image-cleanup
    env: node
    schedule: "0 * * * *"
    buildCommand: npm ci
    startCommand: node scripts/nightlyImageCleanup.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_ACCESS_TOKEN_SECRET
        sync: false
      - key: JWT_REFRESH_TOKEN_SECRET
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRY
        value: 1h
      - key: JWT_REFRESH_TOKEN_EXPIRY
        value: 30d
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CSRF_SECRET
        sync: false
